#!/bin/bash

echo "MD simulation output for vasp5.x"

grep T OSZICAR | awk '{print $3}' > T
grep T OSZICAR | awk '{print $7}' > F
grep T OSZICAR | awk '{print $9}' > E0
grep T OSZICAR | awk '{print $11}' > EK
grep 'total pressure' OUTCAR |awk '{print $4}'>ptot

paste T F E0 EK ptot > md_out

timestep=$(grep POTIM OUTCAR | awk '{print $3}')
TEBEG=$(grep TEBEG OUTCAR | awk '{print $3}')
TEEND=$(grep TEBEG OUTCAR | awk '{print $5}')

TEEND="${TEEND:1}"
TEBEG="${TEBEG::end-1}"

echo $timestep >metadata
echo $TEBEG >>metadata
echo $TEEND >>metadata

