#!/bin/bash
#this function read the number of particles and modify the initial magnetic moment in the INCAR
nums=($(sed -n '6p' POSCAR))
syms=($(sed -n '1p' POSCAR))
n=${#syms[@]}
var=""
for i in `seq 0 $(($n-1))`    #"${nums[@]}"
do
if [[ "${syms[$i]}" == "Co" ]]; then
var=$var${nums[$i]}'*2 '
elif [[ "${syms[$i]}" == "Ni" ]]; then
var=$var${nums[$i]}'*2 '
else
var=$var${nums[$i]}'*0 '
fi
done
echo $var
sed -i.bak "s/239\*0.0\s47\*0.0\s47\*2.0\s48\*2.0\s48\*0.0\s48\*0.0\s2\*0.0/$var/g" INCAR
